(defrule runStart "Start"
  (start)
  =>
  (load "C:/Users/Admin/Documents/GitHub/SBC/materia.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/materias/primero.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/materias/segundo.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/materias/tercero.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/materias/cuarto.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/materias/quinto.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/cambiarEstado.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/print-disponibles.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/updateCorrelativas.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/init.clp")
  (load "C:/Users/Admin/Documents/GitHub/SBC/rules/correlativas.clp")
  (reset)
) 